kahluaband/Homepage_client_ver2.0

app/ticket/(check)/cancel/page.tsx
app/ticket/(check)/reservation/page.tsx
app/ticket/(check)/search/page.tsx
app/ticket/(reserve)/complete/page.tsx
app/ticket/(reserve)/freshman_ticket/page.tsx
app/ticket/(reserve)/general_ticket/page.tsx
components/templates/ticket/CancelRead.tsx
components/templates/ticket/FinalStep.tsx
components/templates/ticket/FreshmanInfo.tsx
components/templates/ticket/GeneralInfo.tsx
components/templates/ticket/InfoTemplate.tsx
components/templates/ticket/MemberSelection.tsx
components/templates/ticket/MustRead.tsx
components/templates/ticket/PartySelection.tsx
components/templates/ticket/PaymentSelection.tsx
components/templates/ticket/TicketSelection.tsx
components/templates/ticket/TicketStatus.tsx
components/templates/ticket/Warning.tsx
tailwind.config.ts

> 
디자인 나온 부분은 모두 구현 완료했슴다~~
> 
>
>

Feat: 예매 페이지 반응형

---

app/about/page.tsx

Design: padding top 제거

---

app/ticket/(check)/search/page.tsx
app/ticket/(reserve)/complete/page.tsx
app/ticket/(reserve)/freshman_ticket/page.tsx
app/ticket/(reserve)/general_ticket/page.tsx
app/ticket/page.tsx
components/data/Information.tsx
components/popups/ticket/LastCheckModal.tsx
components/popups/ticket/LocaltionModal.tsx
components/popups/ticket/ReservedErrorModal.tsx
components/templates/ticket/FinalStep.tsx
components/templates/ticket/FreshmanInfo.tsx
components/templates/ticket/GeneralInfo.tsx
components/templates/ticket/InfoTemplate.tsx
components/templates/ticket/MemberSelection.tsx
components/templates/ticket/TicketOption.tsx
components/ui/DropDownBox.tsx
components/ui/Ticket.tsx
components/ui/TicketDetails.tsx
components/ui/input.tsx
components/util/utils.tsx
public/image/ticket/addplus.svg
public/image/ticket/subtract.svg
tailwind.config.ts

> 
> 
- 모달창 버튼 border-t 설정
- 티켓예매 조회 시 예매번호 입력 10글자로 제한
- 일반 티켓 수 localstorage 오류 수정
- 9월 공연에 맞게 신입생 예매 페이지 막았습니다!
>
>

Fix: Ticket 수정사항 반영

---

tailwind.config.ts

> 
> main page 배경화면에 이미지 로드 안되는 문제 해결하기 위해 이미지 대소문자 수정했습니다
> 
>
>

Fix: main image 대소문자 수정

---

app/ticket/(reserve)/general_ticket/page.tsx
app/ticket/page.tsx
components/popups/ticket/LastCheckModal.tsx
components/popups/ticket/ReservedErrorModal.tsx

Fix: 티켓페이지 수정사항

---

app/ticket/page.tsx
components/popups/ticket/LastCheckModal.tsx
components/popups/ticket/ReservedErrorModal.tsx

Fix: 배포 이슈 해결

---

app/layout.tsx
app/recruit/page.tsx
components/contributors/ContributorCard.tsx
components/contributors/Title.tsx
components/main/About.tsx
components/main/Performance.tsx
components/main/TicketInfo.tsx
components/main/TicketIntro.tsx
components/recruit/SessionCard.tsx

> X
> 1. open graph - title, description 추가
> 2. Img 에서 layout prop 삭제
> X
> X
> X

Feat: og title, description

---

app/layout.tsx
app/page.tsx

>
> font change to roboto
> 
>
>

Feat: font change to roboto

---

app/globals.css
app/layout.tsx
components/util/fonts.tsx

Fix: font preload 설정

---

app/recruit/page.tsx
components/templates/apply/CLInfo.tsx

Design: recruit design 및 지원폼 200자 제한

---

app/recruit/(application)/apply/page.tsx

Feat: console 제거

---

components/contributors/ContributorCard.tsx

> 기수 py-[4px]에서 flex 사용하여 중앙 정렬 하였습니다!
> 
>
>

Design: 기수 flex로 조절

---

app/ticket/(check)/reservation/page.tsx
app/ticket/(reserve)/freshman_ticket/page.tsx
app/ticket/(reserve)/general_ticket/page.tsx
app/ticket/page.tsx
components/data/Information.tsx
components/popups/ticket/LocaltionModal.tsx
components/templates/ticket/FinalStep.tsx
components/templates/ticket/GeneralInfo.tsx
components/templates/ticket/InfoTemplate.tsx
components/templates/ticket/MustRead.tsx
components/templates/ticket/TicketOption.tsx
components/templates/ticket/TicketStatus.tsx
components/ui/DropDownBox.tsx

Fix: QA사항 반영

---

app/ticket/(reserve)/general_ticket/page.tsx
components/templates/ticket/GeneralInfo.tsx
components/templates/ticket/MemberSelection.tsx

Fix: 예매 페이지 인원 선택 오류 해결

---

app/layout.tsx
app/recruit/page.tsx
components/Header.tsx
components/contributors/ContributorCard.tsx
components/contributors/Title.tsx
components/main/About.tsx
components/main/Performance.tsx
components/main/PerformanceCard.tsx
components/main/Recruit.tsx
components/main/TicketInfo.tsx
components/main/TicketIntro.tsx
components/performance/MainContainer.tsx
components/performance/Playlists.tsx
components/recruit/SessionCard.tsx
lib/GoogleAnalytics.tsx

- 구글 애널리틱스 적용하였습니다. 배포 환경 설정에도 추가하였습니다.
- lib 폴더를 생성하여 해당 폴더 내부에서 파일로 관리하고 있습니다. 폴더구조에 변동 있으니 참고 부탁드립니다.
> X
> X

Feat: Google Analytics 적용

---

app/recruit/page.tsx
components/Header.tsx
components/contributors/ContributorCard.tsx
components/contributors/Title.tsx
components/main/About.tsx
components/main/Performance.tsx
components/main/PerformanceCard.tsx
components/main/Recruit.tsx
components/main/TicketInfo.tsx
components/main/TicketIntro.tsx
components/performance/MainContainer.tsx
components/performance/Playlists.tsx
components/recruit/SessionCard.tsx

- #49 
- #62 
- Drawer QA 사항 반영하였습니다.
- sizes props 추가를 통해 정적 로컬 이미지 최적화 진행하였습니다. 
> PR 열어두고 지속적으로 추가하도록 하겠습니다.  특히 모바일 환경에서의 성능 개선을 위주로 작업할 예정입니다.
> 현재 배포 환경에서는 이상 없습니다.
> X
> X

Refactor: 배포 환경 최적화 관련

---

app/ticket/page.tsx
components/popups/ticket/LocaltionModal.tsx

Feat: kakao 타입 정의

---

components/data/Information.tsx
components/data/RecruitingInfo.ts

Feat: Date 동적 생성

---

components/data/Information.tsx
components/data/RecruitingInfo.ts
package-lock.json
package.json

Feat: dayjs 사용

---

components/main/PerformanceCard.tsx

Feat: 반응형 별로 다른 크기의 이미지로 로드

---

app/ticket/(reserve)/complete/page.tsx
components/templates/ticket/TicketStatus.tsx
tailwind.config.ts

Feat: 티켓 정보 업데이트

---

components/admin/AdminHeader.tsx
components/admin/ticketing/TicketLists.tsx

admin header 수정

---

app/ticket/page.tsx

Fix: 신입생 티켓 정보 삭제

---

components/templates/ticket/GeneralInfo.tsx
components/templates/ticket/MemberSelection.tsx

BugFix: local storage 오류 해결

---

app/ticket/page.tsx

Fix: 카카오맵 round 이슈 해결

---

app/ticket/page.tsx

Fix: 예매 페이지 간격 이슈

---

app/ticket/page.tsx

Fix: 지도 간격 이슈

---

components/admin/ticketing/TicketLists.tsx

Feat: 에매번호/전화번호 복사버튼 추가

---

components/templates/ticket/TicketStatus.tsx

[Fix] 공연 날짜 수정

---

app/(admin)/admin/applicant/page.tsx
app/(admin)/admin/ticketing/page.tsx
app/recruit/(application)/notice/page.tsx
app/recruit/page.tsx
components/data/RecruitingInfo.ts

> 
> 1. 티켓 예매자 리스트 엑셀파일로 다운받는 기능 추가하였습니다
> 
>
>

Feat: 엑셀파일 다운로드 추가

---

components/templates/ticket/TicketOption.tsx

Fix: 예매 버튼 비활성화

---

app/layout.tsx
libs/gtag.js

> ex) #102 
> layout 파일에 구글 애널리틱스 적용
env 파일 내용 추가
> 
>
>

Feat: 구글애널리틱스 적용

---

app/recruit/page.tsx
app/ticket/page.tsx
components/data/Information.tsx

Test: test용 isdays true 설정

---

app/(admin)/admin/ticketing/page.tsx
app/mypage/page.tsx
app/recruit/page.tsx
components/Header.tsx
components/admin/AdminHeader.tsx
components/admin/ticketing/TicketLists.tsx
components/contributors/Title.tsx

- #107 
1. 새로운 버전 헤더 작업하였습니다.
2. 데스크탑 버전에서의 경우, KAHLUA 요소에 마우스 호버 시에 추가 요소 (RESERVATION, ANNOUNCEMENT, MYPAGE, ADMIN)이 나타나도록 하였습니다.
3. 모바일 버전의 경우, KAHLUA 요소 클릭 시에 추가 요소가 세부 내용으로 나타납니다.
4. 로그인 / 로그아웃 영역 생성하였습니다. 추후에 로그인 상태관리를 통해 뷰 수정 필요합니다.
> 이슈 참고 부탁드립니다.
>
>

Feat: 헤더 수정 구현

---

components/announcement/posting/CancelPopup.tsx
components/announcement/posting/TopButtons.tsx
components/ui/ButtonModal.tsx

> CancelPopup ButtonModal 공통 컴포넌트 사용하여 구현하였습니다.
> ButtonModal에 x 버튼 cursor-pointer, 빨간 배경에 text-gray-0 추가했습니다! @limgahyun 
>
>

Feat: CancelPopup ButtonModal 컴포넌트 사용하여 구현

---

app/(kahlua)/announcement/post/page.tsx
components/notice/Comment.tsx
components/notice/DeleteCommentPopup.tsx
components/notice/DeletePostPopup.tsx
components/notice/Post.tsx

> 게시글 삭제 모달, 댓글 삭제 모달 - 공통 컴포넌트 사용하는 코드로 수정하였습니다
> 
>
>

Feat: DeletePopup ButtonModal 컴포넌트 사용하여 구현
